repos:
    -   repo: https://github.com/psf/black
        rev: 22.6.0
        hooks:
        -   id: black
    - repo: https://github.com/myint/docformatter
      rev: v1.4
      hooks:
        - id: docformatter
          args: [--in-place]
    -   repo: https://gitlab.com/pycqa/flake8
        rev: 4.0.1
        hooks:
        -   id: flake8
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.3.0
        hooks:
        -   id: check-added-large-files
        -   id: check-case-conflict
        -   id: check-docstring-first
        -   id: check-json
        -   id: check-merge-conflict
        -   id: check-toml
        -   id: check-yaml
        -   id: debug-statements
#        -   id: detect-aws-credentials
        -   id: end-of-file-fixer
        -   id: pretty-format-json
        -   id: sort-simple-yaml
        -   id: trailing-whitespace
#    Commented out for now as it is causing conflict
#    with pyproject.toml and requirements.txt
#    Long term solution is to unify these using a better dependency management, e.g. `poetry`
#    - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
#      rev: v1.3.0
#      hooks:
#          - id: python-safety-dependencies-check
